# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "xhci_pci" "intel_nvme_remap" "ahci" "nvme" "usb_storage" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
		{ device = "/dev/mapper/crypt";
			fsType = "btrfs";
			options = [ "subvol=root" ];
		};

	boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/eb3bb56a-0a3c-4a49-8af0-8b86d395da2f";

	fileSystems."/.swap" =
		{ device = "/dev/mapper/crypt";
			fsType = "btrfs";
			options = [ "subvol=swap" ];
		};

	fileSystems."/home" =
		{ device = "/dev/mapper/crypt";
			fsType = "btrfs";
			options = [ "subvol=home" ];
		};

	fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/C9B2-00D3";
			fsType = "vfat";
			options = [ "fmask=0077" "dmask=0077" ];
		};

	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
